version: '3'

networks:
    internal:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
          - "8080:80"
        volumes:
          - ./dev:/var/www
          - ./config/nginx:/etc/nginx/conf.d
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
        networks:
          - internal
    php:
        build:
          context: ./config/php
          dockerfile: Dockerfile
        container_name: php
        volumes:
          - ./dev:/var/www
          - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
          - "9000:9000"
        networks:
          - internal
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        # command: --innodb_use_native_aio=0
        ports:
          - "3306:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 7212104
        networks:
         - internal
#    phpmyadmin:
#          image: phpmyadmin/phpmyadmin
#          restart: always
#          links:
#            - mysql
#          ports:
#            - 8183:80
#          environment:
#            MYSQL_USERNAME: root
#            MYSQL_ROOT_PASSWORD: 7212104
#            PMA_ARBITRARY: 1

